### PR TITLE
Fix notifications on muted messages for Telegram React

### LINKED ISSUE #113: Muted messages still notify in Telegram React
**Describe the bug**
Since upgrading to 5.5.0-gm, all Telegram messages are being notified of.
Up to this version, muted conversations did not pop a notification.

The only way to avoid it, as of now, is to archive entire threads.

**To Reproduce**

Just get a message in a muted conversation, group, channel or bot.
Even if muted, a notification would still appear on Telegram.

**Expected behavior**
Muted conversations, groups and channels should not be notified of.

**Desktop:**
- OS: Windows 10 x64
- Ferdi Version 5.5.0-gm

Debug information: https://debug.getferdi.com/...

**Additional context**

### PR DESCRIPTION
**Pull request by fr3nd**
Fixes #113

### CODE REVIEW

**Comment by geeks-r-us** [comment]
Please merge this feature

**Comment by vantezzen** [comment]
Thank you for your contribution and sorry for getting back to you on this so late. It looks like you didn't increase the recipe version number as described in https://github.com/getferdi/recipes/blob/master/docs/updating.md. Please increase the recipe version number and repackage the recipe.
If we don't increase the version number, Ferdi won't notice the changes and won't update.

**Comment by fr3nd** [comment]
Done!

**Comment by kytwb** [comment]
@fr3nd thank you for your patience, we will merge this shortly!

**Comment by kytwb** [comment]
This is part of the refactor taking place in https://github.com/getferdi/recipes/pull/292 (for reference).

**Pull request merged**
