### PR TITLE
fix: Update notification handling in hangouts chat

### LINKED ISSUE #102: Google Chat Notification Bubble is broken
**Describe the bug**
The red notification bubble next to the Google Chat Service Icon in the side menu does not show the total number of unread notifications. 

**To Reproduce**
1. Make sure you get a new message in Google Chat
2. Verify the notification bubble which appears on top of Google chat icon in the Ferdi Side bar
4. See error - number of unread notifications are not displayed

**Expected behavior**
On top of the red bubble, the number of unread notifications should appear.

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version Ferdi 5.4.3

### PR DESCRIPTION
**Pull request by sampathBlam**
- Fix the logic of handling direct and indirect messages
- Update the modified class names
- Refactor webview.js
- Update png and svg icons (they were not 1024x1024)
- Fixes #102

Co-Authored-By: Mahadevan Sreenivasan <mahadevan_sv@yahoo.com>

### CODE REVIEW

**Comment by sampathBlam** [comment]
@vantezzen : Can you please review this? Also, if you feel that this PR is good to go, you might need to repackage because of the travis issue. Is there a way in which we can avoid this repackaging in future?

**Comment by vantezzen** [comment]
Looks good to me, will repackage now.

>  there a way in which we can avoid this repackaging in future?
If you have [WSL](https://docs.microsoft.com/windows/wsl/install-win10) installed you could try packaging through that

**Comment by sampathBlam** [comment]
Thanks will install WSL and try next time.

**Comment by vraravam** [comment]
Can I request you to please delete the original PR branch since its been merged? Otherwise, it causes some "noise" in the forked repos as well. Thanks in advance.

**Pull request merged**
