### PR TITLE
Added recipe for Kimai time-tracking instances

### PR DESCRIPTION
**Pull request by kevinpapst**
Hi guys,

tested successfully with latest Franz and Ferdi: Version 5.5.0 (5.5.0.2116)

What is Kimai? [An open source time-tracker written in PHP](https://github.com/kevinpapst/kimai2)
What is Kimai-Cloud? The [SaaS version of Kimai](https://www.kimai.cloud) - free accounts for up to 5 people available.

A free cloud instance is required to test the integration.

Please let me know if you miss anything.

Thanks for your work here!

### CODE REVIEW

**Comment by kytwb** [comment]
@kevinpapst thanks!

**Comment by skipperTux** [comment]
Kimai recipe not showing running timesheet anymore with Kimai 1.15. I assume it has to do with the new timesheet play/stop button (`ticktac-running` / `ticktac-stopped`).

**Comment by skipperTux** [comment]
(Would also be great to be able to change the URL for self-hosted Kimai, see e.g. the [Bitwarden recipe](https://github.com/getferdi/recipes/tree/master/recipes/bitwarden).)

**Comment by vraravam** [comment]
@skipperTux - unfortunately, I dont use kimai - and will not be able to help with the "new timsheet play/stop" functionality.

For the self-hosted url, I can make that change now - and the next nightly should have that bundled

**Comment by skipperTux** [comment]
Thanks for your fast response. Not sure how fix the play/stop issue. I hope @kevinpapst (author of Kimai v2) is also monitoring this conversation and can give us a hint.

**Comment by vraravam** [comment]
merged #717 - if you are on one of the nightlies after the latest release, you should be able to make the same changes in your local - if you don't want to wait for the next nightly.

**Pull request merged**
