### PR TITLE
fix: SetTimeout Slack

### PR DESCRIPTION
**Pull request by mahadevans87**
- People who have slack/whatsapp installed reported losing focus while typing. This could be because there is an endless setTimeout called in these services which causes text fields to lose focus.
  - Remove all setTimeout blocks in slack where a piece if code continuosly clicks on a specific element.

This fix is to address [this ferdi issue](https://github.com/getferdi/ferdi/issues/343)

### CODE REVIEW

**Comment by mahadevans87** [comment]
@kytwb @vantezzen Can you please review this code? This hopefully resolves the losing focus issue - https://github.com/getferdi/ferdi/issues/343 in Ferdi.

**Comment by kytwb** [comment]
@mahadevans87  Can you confirm it still picks up custom Slack icons on new Slack services? 🙏 If yes, looks good to me, nice catch!

**Comment by mahadevans87** [comment]
> 
> 
> @mahadevans87 Can you confirm it still picks up custom Slack icons on new Slack services? 🙏 If yes, looks good to me, nice catch!

Please give me some time. I am trying to gather more evidence on whether this is the exact reason for the lose focus bug.

**Comment by kytwb** [comment]
@mahadevans87 No hurry, I am working on my side as well; I will test locally if I can do it before you 🙏 Otherwise the code changes looks good to me. Thank you for your contributions and involvement 💖

**Comment by mahadevans87** [comment]
> 
> 
> @mahadevans87 No hurry, I am working on my side as well; I will test locally if I can do it before you 🙏 Otherwise the code changes looks good to me. Thank you for your contributions and involvement 💖

Thank you. Btw is there an IRC Channel or some kind of group where we can discuss on the issue rather than filling up the github thread?

**Comment by kytwb** [comment]
@mahadevans87 We sometime communicate via Twitter DMs with @vantezzen, other than that we mostly share everything on GitHub; like this people can easily catch up on discussions, see how we work, learn from us facing issues, sharing our (thought) processes etc. It also forces us to improve how we work/communicate asynchronously, which is great in my opinion! If you'd want to reach out directly, I'm available at amine@mouafik.fr or on [Twitter](https://twitter.com/kytwb) ([vantezzen is on Twitter too!](https://twitter.com/vantezzen)) 🙏

**Comment by mahadevans87** [comment]
@kytwb - We found another fix that should hopefully resolve the focus loss issue. Closing this PR.

**Comment by kytwb** [comment]
Replaced by https://github.com/getferdi/ferdi/pull/610.

**Pull request closed without merging**
