### PR TITLE
fix: Fix typo in name of GitHub Enterprise service

### PR DESCRIPTION
**Pull request by sampathBlam**
- Change name of service from GitHub Entreprise to GitHub Enterprise
- Bump version number to 1.0.1
- Fix typo in class name of index.js
- Update README.md
- Addresses issue #100

### CODE REVIEW

**Comment by vantezzen** [comment]
Thank you for the contribution! I repackaged the recipe as Travis was reporting an error but it's now merged.

**Comment by sampathBlam** [comment]
@vantezzen : Thank you ! Just curious to know what the issue was with travis. There was some error related to the icons in the travis log. But I could not understand it further.

**Comment by vantezzen** [comment]
Travis verifies that the `.tar.gz` archive contains the exact same files with the same contents as the uncompressed folder at `uncompressed/<recipe ID>`.
I suspect you are using Windows to package the recipe? We have noticed before that Windows seems to have problems archiving the `icon.png` file and thus Travis fails. We simply have to run `yarn load github_entreprise && yarn package` on a Linux or macOS machine and the problem fixes itself.

**Comment by sampathBlam** [comment]
@vantezzen : Great ! Thanks for the clarification.

**Comment by vraravam** [comment]
Can I request you to please delete the original PR branch since its been merged? Otherwise, it causes some "noise" in the forked repos as well. Thanks in advance.

**Pull request merged**
