### PR TITLE
Fix UA string for WhatsApp

### PR DESCRIPTION
**Pull request by beppe9000**
It bypasses the outdated chrome message. works for me... the old version was expecting parentheses after ua versions
related: https://github.com/getferdi/ferdi/issues/905

### CODE REVIEW

**Comment by edwardsaunders7** [comment]
I cannot seem to make manual edits to my whatsapp index.js file - even after approving the changes with admin rights, it reverts back to the older version - so I cannot test this

**Comment by beppe9000** [comment]
try moving the whatsapp folder to the dev folder

**Comment by edwardsaunders7** [comment]
I also don't have a \dev folder - where is yours located? These are the files I have:

**Comment by beppe9000** [comment]
inside recipes

**Comment by beppe9000** [comment]
if you are not on windows you probably need to find the equivalent path of this: `C:\Users\Administrator\AppData\Roaming\Ferdi\recipes`

**Comment by beppe9000** [comment]
you can open from here
image

**Comment by edwardsaunders7** [comment]
I don't have a dev folder there either: I'll try making one and doing as you've suggested though, and see if that works

**Comment by beppe9000** [comment]
where is index.js you edited ?

**Comment by edwardsaunders7** [comment]
> you can open from here
> image

Ahh thanks, have found the folder, will try your suggestion now

**Comment by edwardsaunders7** [comment]
Yes! It worked!

**Comment by beppe9000** [comment]
great!

**Comment by edwardsaunders7** [comment]
Thanks for the fix :)

**Comment by beppe9000** [comment]
let's wait for somebody to merge it...

**Comment by edwardsaunders7** [comment]
I'll be making the edits on my personal application in the meantime - good luck, and thanks again

**Review by edwardsaunders7 — APPROVED** [review]

**Comment by kytwb** [comment]
@beppe9000 thank you for your contribution!

I merged despite the failing build as part of the refactor taking place in https://github.com/getferdi/recipes/pull/292.

**Comment by beppe9000** [comment]
great!

**Comment by beppe9000** [comment]
It is unclear to me if I also had to zip it tho

**Comment by kytwb** [comment]
We are refactoring the way recipes are archived, so there is no need to worry about this part of the process anymore.

**Comment by beppe9000** [comment]
perfect !!!

**Pull request merged**
