### PR TITLE
Adds support for indirect messages in Discord

### PR DESCRIPTION
**Pull request by FeikoJoosten**
- Adds support for indirect messages
- Fixes an issue where notifications are no longer detected

Known issues:
- Doesn't properly work when hovering over a guild that has notifications.
- Doesn't properly keep muted guilds while opened in mind.

### CODE REVIEW

**Comment by FeikoJoosten** [comment]
This is pretty much what I've mentioned in #107 as well.

**Comment by kytwb** [comment]
@FeikoJoosten Thank you for your contributions! 💖🙏

**Comment by ray-odoo** [comment]
Should this be working in the version I am using (it isn't, although I do get audio notifications)

image

I get notifications in the vertical panel next to the main one (yellow highlighted area) but not in the main vertical panel (see where LinkedIn shows a notification)

image

**Comment by FeikoJoosten** [comment]
I think this is only in V 5.5.0-gm because you need the indirect notifications support.

**Comment by ray-odoo** [comment]
Great.  I will wait until 5.5 is released then.  Thanks so much for the rapid reply @FeikoJoosten !

**Comment by FeikoJoosten** [comment]
np! You can already install the pre-releae version by going [here](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2).

**Comment by ray-odoo** [comment]
Thanks!! I installed it - it works great.  Notifications are there for Discord, whether it is active or not!

**Comment by FeikoJoosten** [comment]
Glad I could help you out! There are still some issues regarding the detection of Discord notifications, but 95% seems to work fine.

**Pull request merged**
