### PR TITLE
Fix Protonmail unread counter

### PR DESCRIPTION
**Pull request by panz3r**
Update the way the value of unread counter for Protonmail is retrieved

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
Please also include the changed `all,json`. This should have been auto-generated when you ran `pnpm run package`

**Comment by panz3r** [comment]
Hi @vraravam,

Thanks for the quick review, I added the updated `all.json` file.

To update the recipe I followed the steps detailed inside `docs/updating.md` and I'd suggest to add the `pnpm run package` step there since it's not currently listed.

**Comment by vraravam** [comment]
> I'd suggest to add the `pnpm run package` step there since it's not currently listed.

Thanks for the suggestion - I just did that. Please review the new version of `updating.md`

**Review by vraravam — APPROVED** [review]

**Comment by kytwb** [comment]
@all-contributors please add @panz3r for code

**Pull request merged**
