### PR TITLE
enterprise-owa packaged and vs code devcontainer

### PR DESCRIPTION
**Pull request by tfehren**
Hi @vantezzen,
thank you for the quick merge and your feedback.

- As you suggested I have packaged the recipe.
- Also in the merge request are the vscode config files used to run npm in a devcontainer.

### CODE REVIEW

**Comment by tfehren** [comment]
@vantezzen Sorry, I just saw that you already packaged my recipe. So probably you won't need the package.

- I added a default URL and packaged the recipe.
- If you want you can add the vscode devcontainer config.

**Comment by vantezzen** [comment]
> Sorry, I just saw that you already packaged my recipe
Please keep in mind that you'll have to repackage every time you make a change in the source files - otherwise Ferdi will not see those changes.

The VSCode DevContainer looks good! Could you please resolve the merge conflicts on this PR? GitHub gives you instructions on how to do that: Please select to keep _your changes_

**Comment by tfehren** [comment]
@vantezzen not sure I can do that as I do not have write access...
image

**Comment by kytwb** [comment]
@tfehren The message says you need write access to merge the pull request 🙏 To resolve the merge conflict, you will have to synchronize your branch `tfehren:master` with `getferdi:master`. You can find more on how-to sync your fork [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

**Comment by tfehren** [comment]
@kytwb thanks for your patience 🙏. Your link helped :)

**Comment by tfehren** [comment]
Anything I still need to do here?

**Comment by vantezzen** [comment]
No, nothing more to do. Thank you for your contribution!

**Pull request merged**
