### PR TITLE
Remove references to 'Ferdi.clearStorageData' and directly send message to the host via ipc

### PR DESCRIPTION
**Pull request by vraravam**
Needs to be merged in tandem with getferdi/ferdi#1987

### CODE REVIEW

**Comment by kris7t** [comment]
Wouldn't exposing a helper method on the `Ferdi` object (i.e., `RecipeWebview`) that sends the IPC message instead of sending it manually be cleaner?

**Comment by vraravam** [comment]
> Wouldn't exposing a helper method on the `Ferdi` object (i.e., `RecipeWebview`) that sends the IPC message instead of sending it manually be cleaner?

It was like that before - but, I thought the level of indirection might be unnecessary. If that indirection is actually better, then this PR can be abandoned, and the changes in the main one can be reduced. Please confirm which direction to go for.

**Comment by vraravam** [comment]
@kris7t - I have reverted parts of both the PRs to follow the suggestion that you had. Please review

**Review by mhatvan — APPROVED** [review]

**Comment by kris7t** [comment]
> It was like that before - but, I thought the level of indirection might be unnecessary.

In my opinion, adding the indirection is good, because it allows for refactoring the IPC message in the future without having to change the recipes yet again. (I guess the same would apply to the `avatar` and `new-window` IPC messages.)

**Comment by vraravam** [comment]
I agree @kris7t - for the same exact reason as you mention above. I will make the change for the `avatar` and `new-window` as well.

**Pull request merged**
