### PR TITLE
feat: add google chat

### PR DESCRIPTION
**Pull request by mhatvan**
Closes https://github.com/getferdi/ferdi/issues/1615

Currently, Google Hangouts and Google Chat seem to be two different services. 

There seems to be no redirect happening from old Hangouts to new Google Chat. 

That's why I added Google Chat, so users can choose to their liking.

### CODE REVIEW

**Comment by mhatvan** [comment]
## Still to do

- fix unsupported browser issue in Google Chat
- count notifications with webview.js

**Comment by vraravam** [comment]
The `hangoutschat` is the same recipe. We should not create a duplicate just for the sake of the different name. The other service has the same `serviceUrl`. Please close this PR.

**Comment by vraravam** [comment]
We need to either implement the solution for the aliases/tags as discussed [here](https://github.com/getferdi/ferdi/issues/1614#issuecomment-875211630). Or a simpler change would be to include this new name in the current existing recipe - thus making it searchable.

**Comment by mhatvan** [comment]
Ohhh, that is highly confusing with the duplicated services..
Just saw hangouts, not hangoutschat

**Comment by vraravam** [comment]
Please close this PR or revert these new files and only have the name-change in the pre-existing `package.json` file.

**Comment by vraravam** [comment]
Closing since this is now handled by the aliases PR #607

**Pull request closed without merging**
