### PR TITLE
Implement modifyRequestHeaders for Hangouts and document

### PR DESCRIPTION
**Pull request by sampathBlam**
- Add an implementation for modifyRequestHeaders in index.js
- This method can be used to modify HTTP request headers from a service
- Add documentation for modifyRequestHeaders method
- Modify recipe version
- Fix for  getferdi/ferdi#621

Co-Authored-By: Mahadevan Sreenivasan <mahadevan_sv@yahoo.com>

### CODE REVIEW

**Comment by kytwb** [comment]
@sampathBlam Did you re-package the recipe? Looks like the CI is failing on that, but maybe that's due to https://github.com/getferdi/recipes/issues/130. Otherwise LGTM! 💪🙏

**Comment by sampathBlam** [comment]
@sampathBlam : I packaged it using WSL in windows as @vantezzen once stated that that might package it properly instead of packaging it in windows. Anyway, I will try repackaging again now.

**Comment by sampathBlam** [comment]
@kytwb : Tried repackaging using WSL. But no luck :(

**Comment by kytwb** [comment]
@sampathBlam No worries then 🙏 Sorry for the inconvenience, will address via #130.

**Pull request merged**
