### PR TITLE
Fix message count for Fastmail going to 0

### PR DESCRIPTION
**Pull request by nathanaelhoun**
When all the emails are read in Fastmail, the badge disappears and the `document.querySelector()` returns nothing.

With the previous code, this made the badge never disappear. This PR fixes this behaviour by introducing a default value of `0`.

Tested for a few days with both Fastmail and Fastmail beta.

### CODE REVIEW

**Comment by kytwb** [comment]
Thanks for the contribution.

**Comment by vraravam** [comment]
Without a bump in the `version` in both the `package.json` of the recipe and the `all.json`, this will not be picked up in the user's machine when they install the new version of Ferdi which contains the updated recipe.

Please see the `updating.md` file for the checks to be done while submitting a PR for enhancing an existing recipe.

**Comment by kytwb** [comment]
Done via 96cd479.

**Comment by nathanaelhoun** [comment]
Sorry, I somehow missed `updating.md` file (was searching for a `CONTRIBUTING.md` and missed the `docs/` directory :facepalm:). Thankks @kytwb for fixing this for me.

**Comment by kytwb** [comment]
@all-contributors please add @nathanaelhoun for code

**Pull request merged**
