### PR TITLE
Use imagemin to minify images

### PR DESCRIPTION
**Pull request by vraravam**
Use npm package `imagemin` to incorporate a script that can minify images without any other external installed software. Since this is now incorporated into the code, it should produce much more consistent results in any other dev machine.

### CODE REVIEW

**Comment by vraravam** [comment]
@kytwb - this also is the same image minification done for this repo using `imagemin`

**Comment by vraravam** [comment]
As a suggestion, once this is merged, maybe this can be included as a pre-requisite step to be done by each PR for a recipe (so that the git repo is not bloated with multiple versions of binary image files. So, adding this to the PR template as well as the GH actions for CI as checks prior to PR approval.

**Comment by vraravam** [comment]
@kytwb - can you please merge this PR as well?

**Comment by kytwb** [comment]
@vraravam done, thanks!

**Comment by kytwb** [comment]
@vraravam I reverted the merge.

It seemed like a lot of PNG assets were now empty:

```
recipes/zimbra:
total 40
-rw-r--r--  1 kytwb  staff  172 Sep 22 19:57 README.md
-rw-r--r--  1 kytwb  staff    0 Oct 10 04:30 icon.png
-rw-r--r--  1 kytwb  staff   92 Oct 10 04:30 icon.svg
-rw-r--r--  1 kytwb  staff  120 Sep 22 19:57 index.js
-rw-r--r--  1 kytwb  staff  290 Sep 22 19:57 package.json
-rw-r--r--  1 kytwb  staff  324 Sep 22 19:57 webview.js

recipes/zoho:
total 112
-rw-r--r--  1 kytwb  staff    201 Sep 22 19:57 README.md
-rw-r--r--  1 kytwb  staff      0 Oct 10 04:30 icon.png
-rw-r--r--  1 kytwb  staff  38113 Oct 10 04:30 icon.svg
-rw-r--r--  1 kytwb  staff     60 Sep 22 19:57 index.js
-rw-r--r--  1 kytwb  staff    322 Oct 10 04:30 package.json
-rw-r--r--  1 kytwb  staff    226 Sep 22 19:57 webview.js

recipes/zulip:
total 248
-rw-r--r--  1 kytwb  staff   3224 Sep 22 19:57 CODE_OF_CONDUCT.md
-rw-r--r--  1 kytwb  staff   1067 Sep 22 19:57 LICENSE
-rw-r--r--  1 kytwb  staff    256 Sep 22 19:57 README.md
-rw-r--r--  1 kytwb  staff      0 Oct 10 04:30 icon.png
-rw-r--r--  1 kytwb  staff  99564 Sep 22 19:57 icon.svg
-rw-r--r--  1 kytwb  staff   3315 Sep 22 19:57 index.js
-rw-r--r--  1 kytwb  staff    376 Sep 22 19:57 package.json
-rw-r--r--  1 kytwb  staff    304 Sep 22 19:57 webview.js
```

**Comment by vraravam** [comment]
sorry @kytwb - I did a random sampling to open and view the images. Thanks for reverting. Will be more careful next time.

**Comment by vraravam** [comment]
btw - I am using the latest nightly, and I have Zoho in my services - but, I see the image/icon on the left sidebar - not sure why this is working?
Screen Shot 2020-10-10 at 9 16 50 AM

**Comment by kytwb** [comment]
Two things on the latest nightly (5.6.0-nightly.5):

1. I see the following error in **View** > **Toggle Developer Tools**:

```
/Applications/Ferdi.app/Contents/Resources/app.asar/stores/RecipesStore.js:1 Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Applications/Ferdi.app/Contents/Resources/app.asar.unpacked/recipes/all.json
```

Which could explain why the recipes don't get updated. 
It might originate from https://travis-ci.org/github/getferdi/ferdi/jobs/734412620#L198.

2. I went to double-check and we didn't increase the version of the recipes when optimizing the icons, so the recipes would not get updated within Ferdi.

**Comment by vraravam** [comment]
Valid concern @kytwb - but, the `recipes` in the main codebase (`ferdi`) is a submodule - and that is not updated by me in any of my commits/PRs.

**Comment by kytwb** [comment]
The issue resolved itself with 5.6.0-nightly.6 (automatic build); I may have made a wrong choice while doing a manual merge of develop into nightly when fine-tuning the build scripts.

**Pull request merged**
