### PR TITLE
feature: Add jitsi recipe for ferdi

### PR DESCRIPTION
**Pull request by sampathBlam**
- Add packaged recipe for jitsi recipe
- Implement minimal version of webview.js and index.js
- No extra implementation has been done w.r.t. notifications/messages
- Addresses feature request #104

### CODE REVIEW

**Comment by sampathBlam** [comment]
@kytwb @vantezzen  : I have added a Jitsi recipe for ferdi. Can you pls review the same? 
Also, the travis build is failing, probably because of the same packaging issue in windows.

**Comment by vantezzen** [comment]
It looks like you currently have no notification support. I'd suggest adding this to `webview.js`:

```Javascript
module.exports = (Ferdi) => {
  function getMessages() {
    const badges = [...document.querySelectorAll('.badge-round')];
    const messages = badges.reduce((currentValue, element) => currentValue + Number(element.innerText), 0);

    Ferdi.setBadge(messages);
  }

  Ferdi.loop(getMessages);
}
```

**Comment by sampathBlam** [comment]
@vantezzen : Thanks for identifying the notification badge class in jitsi and providing the code for webview.js. I have updated the PR with the above code.

**Comment by vantezzen** [comment]
No problem. Is this PR ready to merge? If so, I would repackage the recipe and merge

**Comment by sampathBlam** [comment]
Yes it is 😊 pls proceed.

**Comment by vantezzen** [comment]
Thank you for your contribution, the recipe is now merged

**Comment by vraravam** [comment]
Can I request you to please delete the original PR branch since its been merged? Otherwise, it causes some "noise" in the forked repos as well. Thanks in advance.

**Pull request merged**
