### PR TITLE
chore: upgrade dependencies to latest

### PR DESCRIPTION
**Pull request by mhatvan**
- upgrade all dependencies to latest
- add `--report-unused-disable-directives` flag to lint script
- remove unused files reported by `unicorn/no-empty-file`
- minor cleanup of circuit recipe
- remove `webview.js` check in `package.js`

### CODE REVIEW

**Comment by mhatvan** [comment]
@vraravam there was a `webview.js` check in `package.js` that I removed, is that okay? 

In the end we would keep empty files that have no use, but not sure if it would crash without a `webview.js`.

**Comment by vraravam** [comment]
hi @mhatvan - sorry, I had just committed the `circuit` fix due to a different PR that I was making and testing.

Also, yes, I think Ferdi would crash without a `webview.js` (even if its empty).

Please rebase from `master` and fix the conflicts.

**Comment by mhatvan** [comment]
Can be improve ferdi to not require webview if it's empty?

**Review by vraravam — APPROVED** [review]

**Comment by franzbischoff** [comment]
Some workspaces don't have the 'o' in the URL and 'board' is on the singular. So setting the Team brings the user to an unknown workspace.

Mine for example is https://app.zenhub.com/workspaces/phd-thesis-5eb2ce34f5f30b3aed0a35af/board

**Pull request merged**
