### PR TITLE
fix: Rocket.Chat tab doesn't display notifications

### PR DESCRIPTION
**Pull request by mhatvan**
Closes https://github.com/getferdi/ferdi/issues/1599

### CODE REVIEW

**Comment by mhatvan** [comment]
@vraravam Quite certain that the code is correct but didn't find a way to test it.
How to test the badge appearing? When I `console.log` locally it never seems to go into the `webview.js` file...

**Comment by vraravam** [comment]
@mhatvan - you can do it in 2 ways:
1. Run the app in dev mode, register the service that you want to test, make changes in the `FerdiDev` profile folder (same parent location as the main runtime - just that the folder is `FerdiDev` as opposed to `Ferdi`). You can also use the `View > Toggle Service Developer Tools` menu item to review and check whether the css selectors are fine.
2. Run the app in real (production) mode. Sign up for the service (rocket chat), and close Ferdi, edit the recipe config files and test.

But you will still need to have signed up for rocket.chat and sign into your real account, and have someone send you a message that you then *do not read* - so that the "unread count" stays there.

**Comment by mhatvan** [comment]
Thank you for the detailed explanation!

I used the second way, edited the prod app with my code changes, both direct and indirect messages work as expected ;)

**Review by vraravam — APPROVED** [review]
LGTM (I don't have a login into rocket.chat - trusting that @mhatvan has run this locally and verified that this works)

**Pull request merged**
