### PR TITLE
Fix user agents override methods

### PR DESCRIPTION
**Pull request by kytwb**
For https://github.com/getferdi/recipes/issues/114, https://github.com/getferdi/ferdi/issues/536, https://github.com/getferdi/ferdi/issues/603, https://github.com/getferdi/ferdi/issues/598, https://github.com/getferdi/ferdi/issues/601, and potentially https://github.com/getferdi/ferdi/issues/475.

### CODE REVIEW

**Comment by kytwb** [comment]
Screen Shot 2020-04-19 at 5 04 46 PM

**Comment by kytwb** [comment]
> Potentially affected: Instagram, Discord, Jira, Kaizala, Messenger, MSTeams, Skype, Steam Chat, WhatsApp.

Tested WhatsApp, Skype, Messenger, Instagram.

**Comment by vantezzen** [comment]
Looks good. Have you tested that WhatsApp is working again?

**Comment by kytwb** [comment]
@vantezzen Confirmed 👌 

Screen Shot 2020-04-19 at 6 05 42 PM

**Comment by sampathBlam** [comment]
@kytwb : I am a bit curious to understand the rationale behind removing the size check for svg icons. Is it not necessary? I do not know much about SVGs either. It would be great if you can provide some clarificiation.

**Comment by kytwb** [comment]
@sampathBlam Thank you for asking @sampathBlam! SVG stands for Scalable Vector Graphics. You don't have to worry about SVG files dimensions as they will render properly as you size them up or down. You can resize SVGs without them ever becoming "pixelated" as they are [_vector graphics_](https://en.wikipedia.org/wiki/Vector_graphics), which is not the case for PNGs as they are _raster graphics_.

**Pull request merged**
